### ISSUE TITLE
Extended glob using ** doesn't work

### ISSUE THREAD

**Issue by fs-c** [xu-cheng/latex-action#101]
See [my fork](https://github.com/fs-c/latex-action/actions/runs/3182822290), where I added the following job

```yaml
- name: Compile multiple LaTeX documents in different directories using extended glob with **
  uses: ./
  with:
    root_file: "extglob/**/*.tex"
    glob_root_file: true
    working_directory: test/
    work_in_root_file_dir: true
```

and amended the test directory to look like

```
extglob/
├── subdir1_glob
│   ├── fig.eps -> ../../fig.eps
│   └── main.tex -> ../../eps.tex
├── subdir2_glob
│   ├── fig.eps -> ../../fig.eps
│   └── main.tex -> ../../eps.tex
└── subdir3_glob
    ├── fig.eps -> ../../fig.eps
    ├── main.tex -> ../../eps.tex
    └── subdir31_glob
        ├── fig.eps -> ../../fig.eps
        └── main.tex -> ../../eps.tex
```

Contrary to my expectations, the .tex file in subdir31_glob wasn't built. Is this a known limitation?

My use case is building all .tex files in all subdirectories. Perhaps there is another way to achieve this?
