### ISSUE TITLE
When glob_root_file is true,, root_file must be a string

### ISSUE THREAD

**Issue by Freed-Wu** [xu-cheng/latex-action#105]
```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: |
      "*.tex"
    glob_root_file: true
```

cannot work.

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: "*.tex"
    glob_root_file: true
```

can work.

Is it a bug?

**Comment by xu-cheng** [comment]
You need to drop the quotations. Like this:

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: |
      *.tex
    glob_root_file: true
```
