### ISSUE TITLE
[feature] When detect latexmkrc, set args=[] to avoid conflict

### ISSUE THREAD

**Issue by Freed-Wu** [xu-cheng/latex-action#106]
Now I must set args = [] to make latexmkrc can work. So I advise to set args = [], when latexmkrc exist. Or set args = [-pvc-].

```
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          args:
```

```perl
$show_time = 1;
$dependents_phony = 1;
$do_cd = 1;
$bibtex_use = 1.5;

$pdf_mode = 5;
$pdflatex = 'pdflatex -shell-escape -file-line-error -synctex=1 %O %S';
$xelatex = 'xelatex -shell-escape -8bit -file-line-error -no-pdf -synctex=1 %O %S';
$lualatex = 'lualatex -shell-escape -file-line-error -synctex=1 %O %S';
```
