### ISSUE TITLE
How to define TEXINPUT

### ISSUE THREAD

**Issue by JohnTrunix** [xu-cheng/latex-action#108]
Hi guys, first of all cool gh-actions workflow!

I don't have much experience in setting up a workflow and some help would be appreciated.
My folder structure:

-   folder1
    -   file1.tex
-   folder2
    -   file2.tex
-   template.cls

How do I define TEXINPUT that template.cls is found in the building process?

Here my yml:
```yml
name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: |
                      ./ANA1/ANA1_FolgenReihen.tex
                      ./LA1/LA1_Vektoren.tex
              env:
                  TEXINPUTS: "./baposter.cls"
            - name: Generate release tag
              uses: amitsingh-007/next-release-tag@v1.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Release PDF
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.release_tag }}
                  body: |
                      This is an automated release with the latest PDFs.
                      Enjoy the new cheatsheets! :rocket:
                  files: |
                      ANA1_FolgenReihen.pdf
                      LA1_Vektoren.pdf

```

My current Error:
```
! LaTeX Error: File `../baposter.cls' not found.
```

This is also a line in my file1.tex:
```
\documentclass[
    a4paper,
    landscape, 
    fontscale=1.5
    ]{../baposter}
```
