### ISSUE TITLE
Use getnonfreefonts and Arial

### ISSUE THREAD

**Issue by andres-gimenez** [xu-cheng/latex-action#114]
I need to create an arial font document and I want to use getnonfreefonts.

I have this code that works fine.

```
- name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install texmaker
        sudo apt-get install texlive-full
        sudo apt-get install texstudio

    - name: Download non free fonts
      run: |
          wget -q https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts
          sudo texlua ./install-getnonfreefonts
          sudo getnonfreefonts --sys --all

    - name: Download non free fonts
      run: |
        pdflatex  --shell-escape -synctex=1 -interaction=nonstopmode -file-line-error -recorder main.tex
```

But this doesn't work for me

```
 - name: Download non free fonts
      run: |
          wget -q https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        pre_compile: |       
             texlua ./install-getnonfreefonts
             getnonfreefonts --sys --all
```

Can't find uarial.sty font

```
Latexmk: Missing input file 'uarial.sty' (or dependence on it) from following:
  ! LaTeX Error: File `uarial.sty' not found.
```
