### ISSUE TITLE
extra_system_packages doesn't work if glob_root_file is true

### ISSUE THREAD

**Issue by neitzke** [xu-cheng/latex-action#116]
I have a workflow containing the following:
```
      - name: Compile
        uses: xu-cheng/latex-action@2.7.0
        with:
          # working_directory: 
          root_file: test-paper.tex
          glob_root_file: true
          extra_system_packages: "inkscape git xournalpp"
          args: "-f"
        continue-on-error: true
```
This fails, and in the log I find the following:
```
Install inkscape git xournalpp by apk
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
ERROR: 'inkscape git xournalpp' is not a valid world dependency, format is name(@tag)([<>~=]version)
```
If I remove `glob_root_file: true`, then everything works as expected. (It also fails if I set `root_file: "*.tex"` as I originally intended)

It looks to me like, for some reason, the system is trying to install all three packages at once, instead of one at a time.

I experimented a bit: the commit 
https://github.com/neitzke/latex-action/commit/80392976de65e0f62f563864eb0f85588880e7c0
(which just reverses the order in which `extra_system_packages` and `glob_root_file` are processed) fixes the problem for me. But I don't understand at all why the problem exists or why this commit fixes it.
