### ISSUE TITLE
How to compile a single document that is split in different latex files

### ISSUE THREAD

**Issue by maveme** [xu-cheng/latex-action#117]
I am trying to compile a latex file (`main.tex`) that has some `\input{...}` commands relating to other files in the sections folder. However, when I try to run it, it doesn't work.

This is my current `action.yml`:

```
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            sections/introduction.tex
            sections/interviews.tex
            sections/appendix.tex
            main.tex
          continue_on_error: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
```

The output is:

```
LaTeX Warning: Reference `TotPages' on page 1 undefined on input line 94.
[515](repoactions/runs/4304101246/jobs/7504646558#step:4:516)

[516](repoactions/runs/4304101246/jobs/7504646558#step:4:517)

[517](repoactions/runs/4304101246/jobs/7504646558#step:4:518)
! LaTeX Error: File `sections/introduction.tex' not found.
[518](repoactions/runs/4304101246/jobs/7504646558#step:4:519)

[519](repoactions/runs/4304101246/jobs/7504646558#step:4:520)
Type X to quit or <RETURN> to proceed,
[520](repoactions/runs/4304101246/jobs/7504646558#step:4:521)
or enter new name. (Default extension: tex)
[521](repoactions/runs/4304101246/jobs/7504646558#step:4:522)

[522](repoactions/runs/4304101246/jobs/7504646558#step:4:523)
Enter file name: 
[523](repoactions/runs/4304101246/jobs/7504646558#step:4:524)
./docs/2023-chi-lbw-main/main.tex:96: Emergency stop.
[524](repoactions/runs/4304101246/jobs/7504646558#step:4:525)
<read *> 
[525](repoactions/runs/4304101246/jobs/7504646558#step:4:526)
         
[526](repoactions/runs/4304101246/jobs/7504646558#step:4:527)
l.96 \input{sections/introduction}
[527](repoactions/runs/4304101246/jobs/7504646558#step:4:528)
                                  ^^M
[528](repoactions/runs/4304101246/jobs/7504646558#step:4:529)
./docs/2023-chi-lbw-main/main.tex:96:  ==> Fatal error occurred, 
[529](repoactions/runs/4304101246/jobs/7504646558#step:4:530)
no output PDF file produced!
[530](repoactions/runs/4304101246/jobs/7504646558#step:4:531)
Transcript written on main.log.
[531](repoactions/runs/4304101246/jobs/7504646558#step:4:532)
Latexmk: Missing input file 'sections/introduction.tex' (or dependence on it) from following:
[532](repoactions/runs/4304101246/jobs/7504646558#step:4:533)
  ! LaTeX Error: File `sections/introduction.tex' not found.
[533](repoactions/runs/4304101246/jobs/7504646558#step:4:534)
Latexmk: ====List of undefined refs and citations:
[534](repoactions/runs/4304101246/jobs/7504646558#step:4:535)
  Reference `TotPages' on page 1 undefined on input line 94
[535](repoactions/runs/4304101246/jobs/7504646558#step:4:536)
Latexmk: If appropriate, the -f option can be used to get latexmk
[536](repoactions/runs/4304101246/jobs/7504646558#step:4:537)
Latexmk: Getting log file 'main.log'
[537](repoactions/runs/4304101246/jobs/7504646558#step:4:538)
Latexmk: Examining 'main.fls'
[538](repoactions/runs/4304101246/jobs/7504646558#step:4:539)
Latexmk: Examining 'main.log'
[539](repoactions/runs/4304101246/jobs/7504646558#step:4:540)
Latexmk: Summary of warnings from last run of *latex:
[540](repoactions/runs/4304101246/jobs/7504646558#step:4:541)
  Latex failed to resolve 1 reference(s)
[541](repoactions/runs/4304101246/jobs/7504646558#step:4:542)
Latexmk: Errors, so I did not complete making targets
[542](repoactions/runs/4304101246/jobs/7504646558#step:4:543)
Collected error summary (may duplicate other messages):
[543](repoactions/runs/4304101246/jobs/7504646558#step:4:544)
  pdflatex: Command for 'pdflatex' gave return code 1
[544](repoactions/runs/4304101246/jobs/7504646558#step:4:545)
      Refer to 'main.log' and/or above output for details
```
