### ISSUE TITLE
Unpack PDF.zip and commit .pdf to repo

### ISSUE THREAD

**Issue by htjb** [xu-cheng/latex-action#122]
Hi @xu-cheng, great package! I have been trying to use it to render a latex file and then commit it to the repo but I am having trouble. I seem to be struggling at the unzip stage since `unzip` can't find the file. Am I correct in thinking that the `upload-artifcat` action generates a zip file containing the pdf? Any help here would be great! I copied my action below and the repo is [here](https://github.com/htjb/CV). Thanks in advance!

```yaml
name: Build LaTeX Document
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
        
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: CV
          
      - name: 'Unzip project'
        uses: montudor/action-zip@v1.0.0
        with:
         args: unzip CV
      
      - name: GIT commit and push PDF
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add CV.pdf
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
```
