### ISSUE TITLE
Help: How to add custom packages?

### ISSUE THREAD

**Issue by leoniewgnr** [xu-cheng/latex-action#133]
I want to add a custom package, that is uploaded to my repo, but it doesnt work. Would appreciate any help!

My yaml file:
```
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cheat_sheets/data_science_case.tex
      env:
        TEXINPUTS: ".:./cheat_sheets/latex4ei//:"
          
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: data_science_case
        path: ./cheat_sheets/data_science_case.pdf
 ```

But it always gives me this error: `! LaTeX Error: File `latex4ei/latex4ei_sheet.cls' not found.`

Everything is located here: https://github.com/leoniewgnr/DataScienceCheatsheets

**Comment by xu-cheng** [comment]
Please try:
```yaml
- uses: xu-cheng/latex-action@v3
  with:
    root_file: data_science_case.tex
    working_directory: cheat_sheets
```
