### ISSUE TITLE
BIBINPUTS behavior changed between v2 and v3

### ISSUE THREAD

**Issue by dpo** [xu-cheng/latex-action#135]
Hi. Thank you for this excellent Action!

I build LaTeX documents that rely upon a `bib` file stored in a folder pointed to by the `BIBINPUTS` environment variable. I set
```yaml
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            mydoc.tex
          working_directory: paper
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace
        env:
          TEXINPUTS: ".:some/path//:"
          BSTINPUTS: ".:some/other/path"
          BIBINPUTS: ".:some/third/path"
```
All is well with v2. However, if I upgrade to v3, the `bib` file (to be found under `some/third/path/`) is no longer found and the build fails.

Any ideas what could be going wrong?
