### ISSUE TITLE
Error on figure captions

### ISSUE THREAD

**Issue by yunapotamus** [xu-cheng/latex-action#139]
Steps to repro:
Any `\caption{Some caption}` in my document causes the following build errors in this GHA. All of my docs work properly when using `pdflatex` locally.

Build error:
```
) (./Bridges.tex [81]
./Bridges.tex:9: Argument of \caption@@@withoptargs has an extra }.
<inserted text> 
                \par 
l.9 ]{Konigsberg}
                 
./Bridges.tex:9:  ==> Fatal error occurred, no output PDF file produced!
```

I have used both the `figure` environment and the `easyfig` package, and similar errors result in both cases. My latex code is pretty simple:
```
\Figure[
  width=4in, 
  caption={
    An 18th century map of Konigsberg. Is it possible to cross all seven bridges in one trip without crossing the same bridge twice?
  },
  label=fig:konigsberg
]{Konigsberg}
```

And my action:
```
jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Googology.tex
          working_directory: Chapters/
```

Am I doing something wrong? Again, everything works locally.
