### ISSUE TITLE
Extra fonts

### ISSUE THREAD

**Issue by kunguz** [xu-cheng/latex-action#14]
Thank you for putting latex-action together. This is a useful docker indeed!

In my repository, I have some font files that I use under `fonts` folder. However, during the compilation, I got such errors:

```
Please type another input file name
! Emergency stop.
<*> ...our; mag:=1; nonstopmode; input FontAwesome
```

My yml file looks like this, what am I missing basically?

```
name: Compile Latex
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: document.tex
          args: -xelatex -file-line-error -interaction=nonstopmode -shell-escape
```
