### ISSUE TITLE
How to set custom name for compiled pdf instead main.pdf

### ISSUE THREAD

**Issue by Ja7ad** [xu-cheng/latex-action#144]
Hello

I want after build change main.pdf file to another name.

```yml
name: Releaser

on:
  push:
    tags:
      - v*

jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                root_file: main.tex
                
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                    LICENSE
                    main.pdf
```
