### ISSUE TITLE
Latex symbols korean

### ISSUE THREAD

**Issue by Angelk90** [xu-cheng/latex-action#146]
Hi @xu-cheng , congratulations on the project.

I'm having a problem with non-Latin characters, for example I'm trying Korean characters but it gives me an error when generating the file.

```yaml
name: Build PDF from LaTeX Korean
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ./latex/Korean.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: '*.pdf'  # Update with the path to your PDF file
```

Korean.tex

```
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage[latin1]{inputenc}

\title{Getting started}
\author{Korean}

\begin{document}
\maketitle

ㄱㄴㄷㄹ


안녕하세요

\end{document}
```

Error: 

```
./latex/Korean.tex:14: Package inputenc Error: Keyboard character used is undef
ined
(inputenc)                in inputencoding `latin1'.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 �
       �ㄴㄷㄹ
./latex/Korean.tex:14:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Korean.log.
Latexmk: Sometimes, the -f option can be used to get latexmk
Latexmk: Getting log file 'Korean.log'
  to try to force complete processing.
  But normally, you will need to correct the file(s) that caused the
  error, and then rerun latexmk.
  In some cases, it is best to clean out generated files before rerunning
  latexmk after you've corrected the files.
Latexmk: Examining 'Korean.fls'
Latexmk: Examining 'Korean.log'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Korean.log' and/or above output for details
```

So I also tried like this:

Korean.tex

```yaml
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage[utf8]{inputenc}

\title{Getting started}
\author{Korean}

\begin{document}
\maketitle

ㄱㄴㄷㄹ

안녕하세요

\end{document}
```

Error:

```
./latex/Korean.tex:14: LaTeX Error: Unicode character ㄱ (U+3131)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 ㄱ
        ㄴㄷㄹ
./latex/Korean.tex:14:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Korean.log.
Latexmk: Sometimes, the -f option can be used to get latexmk
Latexmk: Getting log file 'Korean.log'
Latexmk: Examining 'Korean.fls'
Latexmk: Examining 'Korean.log'
  to try to force complete processing.
  But normally, you will need to correct the file(s) that caused the
  error, and then rerun latexmk.
  In some cases, it is best to clean out generated files before rerunning
  latexmk after you've corrected the files.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Korean.log' and/or above output for details
```
