### ISSUE TITLE
Permission problem with inkscape when recompiling with self hosted runner

### ISSUE THREAD

**Issue by Milokita** [xu-cheng/latex-action#147]
# Problem
 With inkscape package installed, the pdf generated from svg would belong to root user, causing the github action can't clean up the temp file from the self-hosted runner.

# Github script
```
 name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          #pre_compile: "latexmk -C"
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          texlive_version: 2023
          extra_system_packages: "inkscape"
          continue_on_error: true
          args: "-pdf -file-line-error -interaction=nonstopmode"
          post_compile: "latexmk -c"
```

# Github Action Error log
```
Error: File was unable to be removed Error: EACCES: permission denied, unlink '/home/a/gh-actions/actions-runner/_work/repo/ssd/svg-inkscape/xxxx_svg-raw.pdf'
```
