### ISSUE TITLE
LaTeX Error: Something's wrong--perhaps a missing \item.

### ISSUE THREAD

**Issue by AlixANNERAUD** [xu-cheng/latex-action#149]
Hello, first of all, I would like to thank you for this GitHub Action, which is really very convenient.

However, I am encountering a rather strange problem. This error occurs when the action tries to compile my document:
```
./Resume.tex:69: LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.69     \item S
                oliciting partner companies for the collection of apprentice...
./Resume.tex:69:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Resume.log.
Latexmk: Sometimes, the -f option can be used to get latexmk
  to try to force complete processing.
  But normally, you will need to correct the file(s) that caused the
  error, and then rerun latexmk.
  In some cases, it is best to clean out generated files before rerunning
  latexmk after you've corrected the files.
Latexmk: Getting log file 'Resume.log'
Latexmk: Examining 'Resume.fls'
Latexmk: Examining 'Resume.log'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Resume.log' and/or above output for details
```
The lines concerned are as follows:
```tex
  \begin{itemize}
    \item Collecting and optimizing data related to INSA partner companies.
    \item Soliciting partner companies for the collection of apprenticeship tax.
    \item Administrative management of student files.
    \item Conducting alumni surveys for course certification.
  \end{itemize}
```
However, this error does not occur when I compile on my personal computer with the command: 
```shell
latexmk ./Resume.tex -pdf -file-line-error -halt-on-error -interaction=nonstopmode
```
Therefore, I would like to know where I might have gone wrong or if it is a real bug.
I should also point out that [due to a compilation problem with `pdfx.sty`](https://www.reddit.com/r/LaTeX/comments/1ddd7j0/cant_compile_project_due_to_errors_in_tex_live/), I had to add the following line at the top of my main document; otherwise, the action would also produce an error: 
```tex
\RequirePackage[2024-05-01]{latexrelease}
```
Here are also the latex generation lines for my workflow in question:
```
     - name: Build resume
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ./Resume
          root_file: Resume.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Copy resume to static
        run: cp ./Resume/Resume.pdf ./static/Resume.pdf
```
I would also like to point out that it worked perfectly 4 months ago.
You will find the relevant code in this repository: https://github.com/AlixANNERAUD/Resume (I'm using [AltaCV](https://github.com/liantze/AltaCV))
