### ISSUE TITLE
Action should allow for arbitrary environmental variables

### ISSUE THREAD

**Issue by juhannc** [xu-cheng/latex-action#153]
While trying to install a custom package, I realized, that this action does not forward arbitrary environmental variables into the docker container. Thus, the following does not work:

```yaml
name: Build with custom package

on:
  push:
    branches: [main]

env:
  TEXMFLOCAL: /opt/texlive/texmf-local

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build pdf
      uses: xu-cheng/latex-action@v3
      with:
        latexmk_shell_escape: true
        pre_compile: |
          echo "TEXMFLOCAL: ${TEXMFLOCAL}"
          cp -r .github/custom-classes/* ${TEXMFLOCAL}
          mktexlsr && updmap-sys && mktexlsr
        root_file: main.tex
      env:
        TEXMFLOCAL: ${{ env.TEXMFLOCAL }}
```

It would be nice if all env variables (both on workflow level as well as on step level) would be passed into the docker container.

Thanks
