### ISSUE TITLE
How to install extra fonts?

### ISSUE THREAD

**Issue by ludwiglierhammer** [xu-cheng/latex-action#157]
# Problem
In my latex document I use the font ``Verdana``. Locally, I get no errors and the PDF is created. But using your github action the creation fails. I tried two options:

* added ``verdana`` to the ``extra_system_packages``.
* added ``verdana`` to the ``extra_fonts``

# Script 1
```
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          extra_system_packages: verdana
          latexmk_use_lualatex: true
```

# Error 1
```
ERROR: unable to select packages:
  verdana (no such package):
    required by: world[verdana]
```

# Script 2
```
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          extra_fonts: verdana
          latexmk_use_lualatex: true
```

# Error 2
```
cp: can't stat 'verdana': No such file or directory.
```

# Question

How can I use extra fonts without store them in any directories?
