### ISSUE TITLE
Possible confusion because empty options are not allowed

### ISSUE THREAD

**Issue by PHPirates** [xu-cheng/latex-action#16]
Small confusing thing: when you specify empty options like `compiler: #optional` like the current GitHub Actions template suggests, which is for 1.2.0

```yml
- name: Github Action for LaTeX
  uses: xu-cheng/latex-action@1.2.0
  with:
    # The root LaTeX file to be compiled
    root_file: 
    # The working directory for the LaTeX engine
    working_directory: # optional
    # The LaTeX engine to be invoked
    compiler: # optional, default is latexmk
    # Extra arguments to be passed to the LaTeX engine
    args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
    # [Deprecated] Install extra packages by tlmgr
    extra_packages: # optional
    # Install extra packages by apk
    extra_system_packages: # optional
```

Then it will fail (if people fill in just the root_file path) with `/root/entrypoint.sh: line 28: : Permission denied`.

So, I suggest to change the template to something like 

```yml
- name: Github Action for LaTeX
  uses: xu-cheng/latex-action@1.2.0
  with:
    # The root LaTeX file to be compiled
    root_file:
    # The working directory for the LaTeX engine
    #working_directory: # optional
    # The LaTeX engine to be invoked
    #compiler: # optional, default is latexmk
    # Extra arguments to be passed to the LaTeX engine
    #args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
    # [Deprecated] Install extra packages by tlmgr
    #extra_packages: # optional
    # Install extra packages by apk
    #extra_system_packages: # optional
```

so people can simply copy paste the whole thing into their yml file and it should work.
