### ISSUE TITLE
args didn't work ?

### ISSUE THREAD

**Issue by cvermot** [xu-cheng/latex-action#160]
Hi,

I'm trying to pass an extra arg to latexmk (for instance : _-usepretex="\newcommand{\opendys}{}"_).

I pass it via the paths option, but it seems to be ignored.

Here is my M(N)WE :
```
    - name: Produce LaTeX document
      if: steps.check_commits.outputs.has_commits == 'true'
      uses: xu-cheng/latex-action@v3
      with:
        root_file: CoursBIA_complet.tex
        args: -file-line-error -halt-on-error -interaction=nonstopmode -recorder -usepretex="\newcommand{\opendys}{}"
```

But it didn't seems to work. When y check my logs, I see :
```
Run "${GITHUB_ACTION_PATH}/action.sh"
  "${GITHUB_ACTION_PATH}/action.sh"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ...
    INPUT_COMPILER: latexmk
    INPUT_ARGS: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
    ...
::stop-commands::***
...
Category 'other':
  Rerun of 'pdflatex' forced or previously required:
    Reason or flag: 'Initial setup'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'lualatex  -file-line-error -halt-on-error -interaction=nonstopmode -recorder  "CoursBIA_complet.tex"'
------------
This is LuaHBTeX, Version 1.18.0 (TeX Live 2024) 
```
Same problem if I simplify my args to "args: -file-line-error -halt-on-error -interaction=nonstopmode -recorder -usepretex".

Is there any known bugs on the args parameter ?
