### ISSUE TITLE
Question: How to run xelatex -> bibtex -> xelatex*2

### ISSUE THREAD

**Issue by Cierra-Runis** [xu-cheng/latex-action#166]
My current workflow file as below:

```yaml
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: math.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: math.pdf
```
