### ISSUE TITLE
Still need the `extra_packages`

### ISSUE THREAD

**Issue by Jeff-Tian** [xu-cheng/latex-action#19]
Noticed the `extra_packages` argument was removed recently, but in my case even with full TexLive I still need to install one extra package: `fduthesis`. Would it be possible to add the `extra_packages` back?

**Comment by xu-cheng** [comment]
Are you sure? TeXLive with full scheme should already have everything installed.

**Comment by Jeff-Tian** [comment]
Oh I didn't explain it clearly. I am using a `Tex` template made by Stone Zeng called [`fduthesis`](https://github.com/stone-zeng/fduthesis`) and it has been published to `CTAN` and can be installed by `tlmgr install fduthesis`. My `tex` file is based on it.

**Comment by Jeff-Tian** [comment]
Never mind, I forked your action and get the `extra_packages` back. To elaborate more:
Use `fduthesis` as the `extra_package` will build something like this: https://latex.jiwai.win/fduthesis.pdf.

```
      - name: Test fduthesis
        uses: ./
        with:
          root_file: fduthesis.tex
          extra_packages: fduthesis
          working_directory: test/
          compiler: arara
          args: "--verbose"
```
