### ISSUE TITLE
Bibliography is not compiled

### ISSUE THREAD

**Issue by majkrzak** [xu-cheng/latex-action#2]
When I'm building LaTeX document with your action, I'm not getting the Bibliography section created.

`action.yaml`
```yaml
name: Compile LaTeX paper
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Git
      uses: actions/checkout@v1
    - name: LaTeX
      uses: xu-cheng/latex-action@master
      with:
        root_file: paper.tex
        compiler: lualatex
        working_directory: paper/
    - name: Artifact
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: paper/paper.pdf
```

`paper.bib`
```bib
@techreport{rfc793,
  author = {J. Postel},
  title = {Transmission Control Protocol},
  howpublished = {Internet Requests for Comments},
  type = {RFC},
  number = 793,
  year = {1981},
  month = {September},
  publisher = {RFC Editor},
  doi = {10.17487/RFC0793}
}
```

`paper.sty`
```tex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{paper}
\LoadClass[
    10pt,
    a4paper,
    twocolumn,
    twoside
]{article}
\RequirePackage{biblatex}
```

`paper.tex`
```tex
\documentclass{paper}
\bibliography{paper}
\begin{document}
\cite{rfc793}
\printbibliography
\end{document}
```

log
```
Run xu-cheng/latex-action@master
/usr/bin/docker run --name df7dcc3fb0490aa87451ca65cc3c410a29885_688896 --label 0df7dc --workdir /github/workspace --rm -e INPUT_ROOT_FILE -e INPUT_COMPILER -e INPUT_WORKING_DIRECTORY -e INPUT_ARGS -e INPUT_EXTRA_PACKAGES -e INPUT_EXTRA_SYSTEM_PACKAGES -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/lirpc/lirpc":"/github/workspace" 0df7dc:c3fb0490aa87451ca65cc3c410a29885  "paper.tex" "paper/" "lualatex" "-pdf -file-line-error -interaction=nonstopmode" "" ""
lualatex: unrecognized option '-pdf'
This is LuaTeX, Version 1.10.0 (TeX Live 2019) 

kpathsea: Running mktexfmt lualatex.fmt
mktexfmt [WARNING]: resetting $HOME value (was /github/home) to root's actual home (/root).
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt:   /opt/texlive/texdir/texmf-dist/web2c/fmtutil.cnf
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /root/texlive/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /root/texlive/texmf-var/web2c
mktexfmt [INFO]: --- remaking lualatex with luatex
mktexfmt: running `luatex -ini   -jobname=lualatex -progname=lualatex lualatex.ini' ...
This is LuaTeX, Version 1.10.0 (TeX Live 2019)  (INITEX)
 restricted system commands enabled.
(/opt/texlive/texdir/texmf-dist/tex/generic/tex-ini-files/lualatex.ini
(/opt/texlive/texdir/texmf-dist/tex/generic/tex-ini-files/luatexconfig.tex
(/opt/texlive/texdir/texmf-dist/tex/generic/tex-ini-files/pdftexconfig.tex))
(/opt/texlive/texdir/texmf-dist/tex/latex/base/latex.ltx
(/opt/texlive/texdir/texmf-dist/tex/latex/base/texsys.cfg)
./texsys.aux found


\@currdir set to: ./.
```

**Comment by xu-cheng** [comment]
If you want to use LuaLaTeX instead of pdfLaTeX, you should try:
```
- name: LaTeX
      uses: xu-cheng/latex-action@master
      with:
        root_file: paper.tex
        args: "-lualatex -file-line-error -interaction=nonstopmode"
        working_directory: paper/
```
This tells latexmk to use lualatex.
