### ISSUE TITLE
How can i compile multiple files with this action?

### ISSUE THREAD

**Issue by antoniogamiz** [xu-cheng/latex-action#23]
I know I can compile one foñe, with `root_file` argument, but I have a lot of differents file to compile. How can i do that?

**Comment by krook1024** [comment]
I am interested too.

**Comment by xu-cheng** [comment]
You can just run the action multiple times, like:

```yaml
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: doc1.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: doc2.tex
```

**Comment by antoniogamiz** [comment]
> I am interested too.

As the solution provided is not that useful I send you my own solution: https://github.com/antoniogamiz/cuarto-segundo-cuatrimestre/blob/master/.github/workflows/deploy-latex.yml and a bash script inside the docker container https://github.com/antoniogamiz/cuarto-segundo-cuatrimestre/blob/master/compile.sh

**Comment by kai-tub** [comment]
I would also like to compile multiple files with this action.
The ability to use wildcards is very important for my use-case, as it allows me to not know the names of the *.tex files in my pipeline. I am developing a latex beamer template and one test is to simply build a document with all possible options. These documents are generated during the test process and I would like to build all of them at once, without always having to edit the *.yaml file.
I would like to help, but I have very little experience with bash. 

I think this action would become even more awesome if wildcards would be supported. :)

**Comment by xu-cheng** [comment]
@kai-tub For your use case, I think it is more appreciate to use the docker image directly. For example:
```yaml
name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: docker://xucheng/texlive-full:latest
        run: |
          find . -name "*.tex" -exec latexmk -pdf -file-line-error -interaction=nonstopmode {} \;
```
