### ISSUE TITLE
Working directory for compilation

### ISSUE THREAD

**Issue by Zethson** [xu-cheng/latex-action#25]
Hi,

Before actually being able to build my latex file I need to change directory into a specific directory.
The full path results in errors, since pdflatex then doesn't find all required files and just the root.txt file

Basically:

```
      - name: Build thesis
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
```
Should build

```
      - name: Build thesis
        uses: xu-cheng/latex-action@master
        with:
          root_file: RealDirectory/thesis.tex
```

How can I cd into the required directory first and then run the building process from there? (It works locally).
The work-directory parameter doesn't seem to do what I need it to do.

Thank you very much.
