### ISSUE TITLE
[Feature Request] Custom commands before compilation

### ISSUE THREAD

**Issue by Sbozzolo** [xu-cheng/latex-action#29]
Would it be possible to add an option to run custom commands before the LaTeX compilation?

I would like to do some light pre-processing/post-processing to better prepare my papers for submission to arXiv/journals.

**Comment by xu-cheng** [comment]
What kinds of the command you want to run? Does it require a TeXLive environment? Because if not, you can just create a separate action step:

```yaml
- run: |
    <your command>
- uses: xu-cheng/latex-action@master
  ...
```

Anyway, I will add a new option to run preflight commands.
