### ISSUE TITLE
Allow skipping of root_file for Makefile instead

### ISSUE THREAD

**Issue by matthewfeickert** [xu-cheng/latex-action#30]
Hi. With the addition of [release `v1.3.0`](https://github.com/xu-cheng/latex-action/releases/tag/1.3.0) you've very nicely added `pre_compile` and `post_compile` options &mdash; which are great! This immediately made me want to use `Makefile`s with `pre_compile` by using a pattern of

```yaml
- name: Compile LaTeX document
  uses: xu-cheng/latex-action@1.3.0
  with: 
    extra_system_packages: "make"
    pre_compile: "make"
    root_file: file_name.tex # root_file is required by latex-action
    post_compile: "ls -lhtra"
```

where `root_file` is either the same document that would be build by `make` or is a dummy file &mdash; this works! With this pattern it would be a lot nicer to be able to either skip `root_file` with something like

```yaml
- name: Compile LaTeX document skipping root_file
  uses: xu-cheng/latex-action@1.X.Y
  with: 
    extra_system_packages: "make"
    pre_compile: "make"
    root_file: null
```

or to allow for there to be an option to use a Makefile if `make` has been installed through `extra_system_packages` _instead_ of `root_file`

```yaml
- name: Compile LaTeX document with a Makefile
  uses: xu-cheng/latex-action@1.X.Y
  with: 
    extra_system_packages: "make"
    makefile_target: "default"
    post_compile: "ls -lhtra"
```

The added bonus of this option is that most people end up writing `Makefiles` for their LaTeX project, so this would allow them to test their whole system more directly.

What do you think of this idea? I didn't see anyone else mention Makefiles in the Issues, so I hope I didn't miss a discussion that already occurred on this.

Also, thank you so much for creating this GitHub Action! It is so helpful and has already been of great use in a few projects!

**Comment by xu-cheng** [comment]
This action is created for the most common case to compile latex documents.  As for your use case, I think it is drastically different than what this action is for. In fact, what you actually need is a latex environment instead of a latex action. I strongly suggest you to use the latex docker image directly. 

```yaml
name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: docker://xucheng/texlive-full:latest
        run: |
          apk --no-cache add make
          make
```

**Comment by matthewfeickert** [comment]
> This action is created for the most common case to compile latex documents.

Sure. That's understandable.

> I strongly suggest you to use the latex docker image directly.

Your example above would make this very easy, but unfortunately it is invalid GitHub Actions syntax. It will error with

```
a step cannot have both the `uses` and `run` keys
```

I know that the [job level container option](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) but that of course makes things more difficult if you wan to use any additional actions for deployment post-compile.

**Comment by matthewfeickert** [comment]
Though it turns out that your solution mixed [with overriding the `entrypoint`](https://github.community/t5/GitHub-Actions/Workflow-fails-when-running-steps-in-a-container/m-p/29826/highlight/true#M386) works:

```yaml
- name: Compile LaTeX document
  uses: docker://xucheng/texlive-full:latest
  with:
    entrypoint: /bin/sh
    args: |
      -c "\
      apk --no-cache add make && \
      make"
```

:+1:
