### ISSUE TITLE
sh: xindy: not found

### ISSUE THREAD

**Issue by jy95** [xu-cheng/latex-action#32]
Hello,

Thanks for your good Github Actions : I have a problem when using [xindy](https://www.ctan.org/pkg/xindy) with [glossaries](https://www.ctan.org/pkg/glossaries) (I need that to sort my glossary entries with accents) with your action ( I have no problem with that in local with MiKTeX)

![image](https://user-images.githubusercontent.com/9306961/81459247-3ac46b00-919f-11ea-8d63-933921ef7854.png)

For my .latexmkrc, I use the [glossary_latexmkrc](http://ctan.cs.uu.nl/support/latexmk/example_rcfiles/glossary_latexmkrc) from [https://www.ctan.org/tex-archive/support/latexmk/example_rcfiles](https://www.ctan.org/tex-archive/support/latexmk/example_rcfiles). 

```tex
\usepackage[
  toc,
  nonumberlist,
  nogroupskip,
  nopostdot,
  xindy
]{glossaries}
\usepackage{glossary-longbooktabs}
\makeglossaries
```

I checked and in Tex Live, xindy is installed but it seems makeglossaries use perl (which one cannot find it)

Any ideas ?

**Comment by xu-cheng** [comment]
This seems to be an issue of TeXLive that it does not offer xindy binaries for Linux musl environment. The package `xindy.x86_64-linuxmusl` is missing. 

Could you try the following workaround?

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    pre_compile: | 
      ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/xindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/xindy
      ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/texindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/texindy
    root_file: main.tex
```

**Comment by jy95** [comment]
Tested just now : 
![image](https://user-images.githubusercontent.com/9306961/81460452-bde8bf80-91a5-11ea-873c-aa77ea140a52.png)

**Comment by xu-cheng** [comment]
How about:

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    pre_compile: | 
      ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/xindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/xindy
      ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/texindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/texindy
      wget https://sourceforge.net/projects/xindy/files/xindy-source-components/2.4/xindy-kernel-3.0.tar.gz
      tar xf xindy-kernel-3.0.tar.gz
      cd xindy-kernel-3.0/src
      apk add make
      apk add clisp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
      make
      cp -f xindy.mem /opt/texlive/texdir/bin/x86_64-linuxmusl/
    root_file: main.tex
```

**Comment by xu-cheng** [comment]
The root issue is that `xindy.x86_64-linuxmusl` is missing. So you may want to submit to an issue to TeXLive.

**Comment by jy95** [comment]
@xu-cheng It seems we forgot to cd to the working directory so cannot test yet.

![image](https://user-images.githubusercontent.com/9306961/81460992-3b61ff00-91a9-11ea-88ab-7a0a2ab9b910.png)

Feel free to submit an issue to TeXLive : It is the middle of the night in my timezone ^^
(honestly, I found strange this **xindy.x86_64-linuxmusl** is missing )

**Comment by xu-cheng** [comment]
You can just cd it back in the end of precompile script. 

I don’t use xindy by myself. So I will close this issue for now.

**Comment by jy95** [comment]
I think it may be useful to at least mention this weird behaviour some (as glossaries package is often mentionned with xindy )
Do you mind sending a report to TeXLive (or suggest them to create an package on [Alpine](https://pkgs.alpinelinux.org/packages) ([tutorial](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package)) ) ? 

Thanks for the help anyway.

**Comment by xu-cheng** [comment]
I now added a mention to this in the README. 

I will not report an issue to TeXLive or Alpine, but you are free to do so.

**Comment by jy95** [comment]
@xu-cheng I send them an issue : let's see how it goes.
I would like to suggest you a cleaner solution : 

**workflow.yml**:
```yml
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      # For weird reasons, xindy binaries are not available in Tex Live (xindy.x86_64-linuxmusl) 
      # Github Actions set-output/set-env truncates Multiline Strings so ...
      # https://github.com/xu-cheng/latex-action/issues/32#issuecomment-626086551
      # https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870
      - name: Workaround script for xindy
        run: |
          content="$(tail -n +3 .github/workflows/texlive_workaround.sh)"
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-env name=TEXLIVE_WORKAROUND::$content"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: | 
            ${{ env.TEXLIVE_WORKAROUND }}
          root_file: main.tex
```

**texlive_workaround.sh** : 

```sh
#!/bin/sh
set -e

ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/xindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/xindy
ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/texindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/texindy
wget https://sourceforge.net/projects/xindy/files/xindy-source-components/2.4/xindy-kernel-3.0.tar.gz
tar xf xindy-kernel-3.0.tar.gz
cd xindy-kernel-3.0/src
apk add make
apk add clisp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
make
cp -f xindy.mem /opt/texlive/texdir/bin/x86_64-linuxmusl/
cd ../..
```

**Comment by goerz** [comment]
The [workaround](https://github.com/xu-cheng/latex-action/issues/32#issuecomment-626086551) results in the following error for me:

~~~
...
Executing busybox-1.31.1-r19.trigger
OK: 406 MiB in 160 packages
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  clisp (missing):
    required by: world[clisp]
~~~

**Comment by jy95** [comment]
@goerz Here was the answer I received from [TextLive team](http://ftp.math.utah.edu/pub/texlive-utah-2020/README.html#alpine). Maybe it will help you ...

**Comment by goerz** [comment]
Thanks! I'm not really sure what to do with that, though. I worked around the problem by avoiding `latexmk`, and calling `lualatex` directly (twice). I'm actually not even sure why `latexmk` was trying to invoke `xindy`. My document doesn't have an index.

Wouldn't it be easier to switch the Docker image from Alpine Linux to some other Linux distribution that's fully supported by texlive (using the standard GNU stdlib)?

**Comment by xu-cheng** [comment]
@goerz Please try the updated workaround. The issue is caused due to `clisp` changing the its repo in apk.

> I worked around the problem by avoiding latexmk, and calling lualatex directly (twice). I'm actually not even sure why latexmk was trying to invoke xindy. My document doesn't have an index.

It should be able to disable xindy in latexmk by creating a `.latexmkrc` file. Please refer latexmk's doc on how to do it.

> Wouldn't it be easier to switch the Docker image from Alpine Linux to some other Linux distribution that's fully supported by texlive (using the standard GNU stdlib)?

The reason Alpine is used is because its smaller size. Unfortunately, we cannot easily change the image without causing breakage to existing workflows.

**Comment by cathaysia** [comment]
> 
> 
> How about:
> 
> ```yaml
> - uses: xu-cheng/latex-action@v2
>   with:
>     pre_compile: | 
>       ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/xindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/xindy
>       ln -sf /opt/texlive/texdir/texmf-dist/scripts/xindy/texindy.pl /opt/texlive/texdir/bin/x86_64-linuxmusl/texindy
>       wget https://sourceforge.net/projects/xindy/files/xindy-source-components/2.4/xindy-kernel-3.0.tar.gz
>       tar xf xindy-kernel-3.0.tar.gz
>       cd xindy-kernel-3.0/src
>       apk add make
>       apk add clisp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
>       make
>       cp -f xindy.mem /opt/texlive/texdir/bin/x86_64-linuxmusl/
>       cd ../../
>     root_file: main.tex
> ```

This scripts not work in my work. I install texlive-full on ubuntu-latest, reproduce this problem, and install xindy package solved this. I don't know alpine has this package or not.

All code as flows:
```yaml
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: solve deps
              run: |
                  sudo apt-get update
                  sudo apt-get -y install python3-pip make make
                  sudo apt-get -y install texlive-full xindy
                  sudo pip install -r requirements.txt
            - name: build
              run: |
                  make latexpdf
```
