### ISSUE TITLE
Action hangs indefinitely

### ISSUE THREAD

**Issue by 5N44P** [xu-cheng/latex-action#33]
Hey there! 
I wanted to use this action for a project. I think i did set up it correctly, since it works with a couple other projects.
This time though, it hangs indefinitely at "compile LaTeX document".
Would you be able to help?

I've made a minimum (non-)working example at: 
https://github.com/5N44P/MWE_LATEX_ACTION

**Comment by xu-cheng** [comment]
Sorry but your example is not minimum enough. There are two latex projects in your example. I am not sure which one you have trouble.

I would suggest to compile the project locally using `latexmk -pdf <root tex file>` to troubleshoot your problem.

One possible answer to your problem is that you are using other language or file encoding that does not work well with pdflatex. In this case, you can switch to lualatex. To do that, first verify that your project can be compiled locally using `latexmk -lualatex <root tex file>`. To use lualatex in this action, change the `args` input:

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: main.tex
    args: -lualatex --file-line-error --interaction=nonstopmode
```
