### ISSUE TITLE
Latexmk: Non-existent bbl file 'doc.bbl'

### ISSUE THREAD

**Issue by montao** [xu-cheng/latex-action#35]
Trying to use a bibliography file, the action fails with the following error:

`Latexmk: Non-existent bbl file 'doc.bbl'`

What I tried was the following:

```
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        # The root LaTeX file to be compiled
        root_file: doc.tex
        args: -bibtex
```

It would be much better if there was an example somewhere so that I did not have to guess...

If I run the container locally the following command generates the PDF file with the bibliography

` latexmk -bibtex -f -pdf`

My temporary workaround is to supply the bibliography inline, then it comes out. It did it in the following repo
https://github.com/montao/latex-bib-inline

It would be good if we could let users have instructive examples so that the next guy will not have to guess like I do.

Why does it finish in the container but not in the action pipeline?  I even tried to add a configuration file to make it find the bib file but I had to guess the syntax because the documentation is (deliberately?) incomprehensible and it did not work anyway. 

Is it some issue with the PATH in the pipeline? My repo https://github.com/montao/latex-bib-test
