### ISSUE TITLE
Cannot compile pdflatex

### ISSUE THREAD

**Issue by Huy-Ngo** [xu-cheng/latex-action#39]
Hi, I was trying to use this action for compiling LaTeX and it failed with the following error:

```
/opt/texlive/texdir/texmf-dist/tex/latex/biblatex/biblatex.sty:2175: Text line 
contains an invalid character.
l.2175      \bgroup\nohyphenation#1\egroup^^^
                                             ^200b}}
/opt/texlive/texdir/texmf-dist/tex/latex/biblatex/biblatex.sty:2175:  ==> Fatal
 error occurred, no output PDF file produced!
Transcript written on sample.log.
Collected error summary (may duplicate other messages):
Latexmk: Examining 'sample.log'
  pdflatex: Command for 'pdflatex' gave return code 1
=== TeX engine is 'pdfTeX'
```

[Here](https://github.com/Huy-Ngo/YAltaCV/pull/4/checks?check_run_id=1205534394) is the full log and [here](https://github.com/Huy-Ngo/YAltaCV/blob/action/.github/workflows/compile_latex.yml) is my file for the action:

```yaml
- name: Github Action for LaTeX
        # You may pin to the exact commit or the version.
        # uses: xu-cheng/latex-action@dacf2cfbdd5fd768c2298cbdc9e105bd9ed7f293
        uses: xu-cheng/latex-action@v2
        with:
          root_file: sample.tex
          post_compile: |
            git add sample.pdf
            git commit -m "Generate PDF file"
            git push
```

I'm confused by the error message saying "Text line contains an invalid character" and pointing to a library file. I'm not sure if this is on bibtex side or on my side.
