### ISSUE TITLE
lint with chktex before building

### ISSUE THREAD

**Issue by paddyroddy** [xu-cheng/latex-action#43]
I'm migrating a workflow from Travis where my config file looks like 
```
jobs:
    include:
        - name: chktex & deploy
          services: docker
          script:
              - ./latexdockercmd.sh chktex background.tex | tee /dev/stderr | (! grep -q ^)
              - ./latexdockercmd.sh latexmk -quiet -pdf background.tex
```
and the script file is
```
#!/bin/sh
IMAGE=blang/latex:ctanfull # Modified into ctanfull
exec docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data "$IMAGE" "$@"
```
this has the advantage that the Docker image is pulled only once but can be used for `chktex` & `latexmk`. Is there such a way of doing it with this action?

Thanks!
