### ISSUE TITLE
Set TEXINPUTS variable?

### ISSUE THREAD

**Issue by drupol** [xu-cheng/latex-action#49]
Hello,

Is it possible to set the variable `TEXINPUTS` used by `latexmk` ?
If yes, do you think it would be possible to provide an example?

Thanks.

**Comment by xu-cheng** [comment]
Yes, just set it using GitHub action environment variable. It will be picked up atomically. 

https://docs.github.com/en/actions/reference/environment-variables

**Comment by xu-cheng** [comment]
An example:

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: main.tex
  env:
    TEXINPUTS: some-value
```
