### ISSUE TITLE
Can't find the pdf file although the action completes successfully

### ISSUE THREAD

**Issue by dimpram** [xu-cheng/latex-action#53]
Hello,

I am new to github actions and although i setup a similar gh action like your example, i can't seem to find the produced pdf on my repository.

Here is my action

```yml

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_late"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup git repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Github action for latex
        uses: xu-cheng/latex-action@v2
        with: 
          root_file:
            main.tex

```

and here is my repository files

```
.
├── assets
├── _config.yml
├── _data
│   └── cv.yml
├── Gemfile
├── Gemfile.lock
├── index.html
├── main.tex
├── README.md
└── _site

```

Am i missing something? Shouldn't the pdf appear in the root of the repository?

Thanks in advance

**Comment by xu-cheng** [comment]
Please see https://github.com/xu-cheng/latex-action#where-is-the-pdf-file-how-to-upload-it

**Comment by asafmaman101** [comment]
Having the same issue, looked over [https://github.com/xu-cheng/latex-action#where-is-the-pdf-file-how-to-upload-it](https://github.com/xu-cheng/latex-action#where-is-the-pdf-file-how-to-upload-it)
Yet cannot understand how to end up the action with a pdf file in the repo.
Can someone elaborate more on how to achieve that?

**Comment by dimpram** [comment]
@asafmaman101 the way i ended up doing it is completely avoid using this latex-action and using a docker image of pandoc as an action i generate and commit the resulting pdf back to the main repo.

For example here is my full workflow

```yaml
name: Pandoc
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_latex:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0              # otherwise, you will get failed to push refs to dest repo
      - name: Compile latex with pandoc
        uses: docker://pandoc/latex:2.11.4
        with:
          args: >-  # allows you to break string into multiple lines
            --pdf-engine=xelatex
            --template=_data/template.tex
            -o assets/output.pdf
            _data/cv.yml      # THIS is what you are looking for
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

```

You can find more information here:
- https://github.com/pandoc/pandoc-action-example
- https://github.com/marketplace/actions/github-push

I hope it helps :smiley:
