### ISSUE TITLE
Failed to install xindy on Alpine

### ISSUE THREAD

**Issue by cathaysia** [xu-cheng/latex-action#54]
[This](https://github.com/xu-cheng/latex-action/issues/32#issuecomment-626086551)  does not work in my workflows. I install texlive-full on ubuntu-latest reproduced this problem, then I install xindy package solved this. I don't know alpine has this package or not. If possible,  install xindy package may can fix this problem.

All the code of my workflows as flows:

```yaml
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: solve deps
              run: |
                  sudo apt-get update
                  sudo apt-get -y install python3-pip make make
                  sudo apt-get -y install texlive-full xindy
                  sudo pip install -r requirements.txt
            - name: build
              run: |
                  make latexpdf
```
