### ISSUE TITLE
Build and Upload Artifacts

### ISSUE THREAD

**Issue by Zeyecx** [xu-cheng/latex-action#64]
Hi guys, 
I am compiling the PDF file as follows.

```yml
 - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./docs/paper/
          root_file: rubyger.tex
```
It all works very well too. However, github cannot find the PDF for the upload.

```yml
  - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: rubyger.pdf
```

![image](https://user-images.githubusercontent.com/15014849/121825854-f5813f80-ccb4-11eb-9df3-c6aa10ac2c1f.png)

What am I doing wrong ?
