### ISSUE TITLE
Inkscape Support?

### ISSUE THREAD

**Issue by nikeee** [xu-cheng/latex-action#65]
I'm using the SVg package, which uses a locally installed Inkscape to convert the SVG to something else.
Is it possible to add this to this image or would that be out of scope?

**Comment by xu-cheng** [comment]
You can install Inkscape by yourself. Like:

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: main.tex
    pre_compile: |
       apk --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community add inkscape
```
