### ISSUE TITLE
Compiling the same file multiple times

### ISSUE THREAD

**Issue by Pinzauti** [xu-cheng/latex-action#70]
In order to use [this](https://ctan.org/pkg/frontespizio?lang=en) package I have to compile the same file two times. 
Specifically, I have to compile, in order, `main.tex`, `main-frn.tex` and then again `main.tex`.
Unfortunately, it does not seems to work, as the `main.tex` file is compiled only the first time. Everything works well locally.

Here is the code:

```
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: "tlmgr update --self && tlmgr update --all"
          root_file: |
            main.tex
            main-frn.tex
            main.tex
```

Thanks.

**Comment by xu-cheng** [comment]
The root issue is that `latexmk` does not work well with the package you mentioned. You should be able to reproduce this problem locally as follows. Starting with clean repo, run `latexmk -pdf main; latexmk -pdf main-frn; latexmk -pdf main`. You should see that `latexmk` skips the second compilation as all files are up-to-date.

To address this properly, you should write some custom `.latexmkrc` logic to declare the dependencies between `main-frn` and `main`. Alternatively, you could force `latexmk` compile second time by passing additional `-g` flag, like:
```yaml
- name: Compile LaTeX document
  uses: xu-cheng/latex-action@v2
  with:
    args: "-g -pdf -file-line-error -halt-on-error -interaction=nonstopmode"
    root_file: |
      main.tex
      main-frn.tex
      main.tex
```

Or you could try to compile the documents separately and insert `touch` command to fresh the source file, like:
```yaml
- name: Compile LaTeX document
  uses: xu-cheng/latex-action@v2
  with:
    root_file: |
      main.tex
      main-frn.tex
- run: "touch main.tex"
- name: Compile LaTeX document
  uses: xu-cheng/latex-action@v2
  with:
    root_file: main.tex
```
