### ISSUE TITLE
Because `latexmkrc` may defines `@default_files` should we make 'root_file' as optional

### ISSUE THREAD

**Issue by CAMOBAP** [xu-cheng/latex-action#78]
It seems that make sense to make `root_file` input optional because input files can be defined in `latexmkrc` file

Example repo https://github.com/expresslang/course

Here is how defined files to compile in [`latexmkrc`](https://github.com/expresslang/course/blob/main/tex/latexmkrc#L14)

**Comment by xu-cheng** [comment]
Hi, this action is designed to compile tex document one by one. 

For your use case, I would recommend you to use [texlive-action](https://github.com/xu-cheng/texlive-action) instead, which allows you to run arbitrary commands in a texlive environment.  For example, you have the following GHA:

```yaml
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            latexmk
```
