### ISSUE TITLE
Bring forward pre_compile options to the beginning of the process

### ISSUE THREAD

**Issue by kazutoiris** [xu-cheng/latex-action#84]
In recent days, I found that the `Raleway` font was not available, even though it is a built-in font and is cached.

```
LaTeX Font Warning: Font shape `TU/Raleway(0)/m/sc' undefined
(Font)              using `TU/Raleway(0)/m/n' instead on input line 379.
```

I tried to empty the `/opt/texlive/texdir/texmf-dist/fonts/type1/` directory and finally I could use the font successfully.

Since there is no way to use custom commands before font updates, emptying the type1 folder becomes tricky. So it may be necessary to move the `pre_compile` option to the beginning of the process, or provide a new option at the beginning of the process.

At the same time, I also found that the existence of type1 fonts will lead to the problem of unavailability of built-in fonts easier to occur, perhaps a hidden option can be provided for removing type1 fonts.

Files used for testing:
```tex
\documentclass{article}
\usepackage{fontspec, xunicode, xltxtra}
\setmainfont{Raleway}
\begin{document}
test
\end{document}
```

**Comment by NKID00** [comment]
There's the same problem in my repo while using the font `CMU Serif`. However updating the font cache again after removing type1 fonts would seem to solve this problem, for example:

```yaml
- uses: xu-cheng/latex-action@v2
  with:
    root_file: file1.tex
    pre_compile: rm -rf /opt/texlive/texdir/texmf-dist/fonts/type1/ && fc-cache -f
```
