### ISSUE TITLE
EPS to pdf conversion support

### ISSUE THREAD

**Issue by DriesMeerman** [xu-cheng/latex-action#93]
I am trying to use eps images in my file but compilation now fails.
I'm not fully sure whether this is due to the eps files or due to my nesting of subfiles.

Steps to reproduce:
1. Have a latex document using subfiles 
2. Load an image asset of eps filetype.
3. Conversion to pdf fails

Error:
```
Logfile claimed conversion from 'chapters//../assets/model_variations/jira_set/line/single_bow_variation_model_performance.eps' to 'chapters//../assets/model_variations/jira_set/line/single_bow_variation_model_performance-eps-converted-to.pdf'.  But:
   Output file does not exist
```

I think a package is not installed in the docker container that would normally be used for this conversion.
https://tex.stackexchange.com/questions/76455/converted-xxx-eps-converted-to-pdf-not-found

**Comment by xu-cheng** [comment]
By default, latex does not allow creating file outside of the directory of the root tex file. You need enable shell escape to allow it.

I will close this issue as it is unrelated to this GitHub action. Please consider to submit similar questions for latex usage in stackexchange or other QA forum in the future.

**Comment by MartinRJDagleish** [comment]
Hey, 
I can't seem to find the problem as I am using `--shell-espace`. I tried it with your given option and also added it manually with `args`, but both did not seem to work. 

![image](https://user-images.githubusercontent.com/52655835/198892253-2767c30a-6d28-409f-a46f-efae2a445e86.png)

The image should be within a subfolder. 

My GitHub workflow: 
```yml
# .github/workflows/build.yml
name: LuaTeX Compile Script 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Release", "main" ]
  pull_request:
    branches: [ "Release", "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v3
      # - name: Cd to Skript dir 
      #   run: cd Skript_LaTeX/Skript_current
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: Skript_LaTeX/Skript_current
          root_file: Skript_current.tex
          args: --synctex=1 --shell-escape 
          latexmk_use_lualatex: true
          # latexmk_shell_escape: true
      - name: Test for cwd 
        run: pwd 
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Skript_LaTeX/Skript_current/Skript_current.pdf
  ```
