### ISSUE TITLE
No PDF created

### ISSUE THREAD

**Issue by fbuedding** [xu-cheng/latex-action#94]
Workflow doesn't fail and runs through, but pdf is not created

Worklfow:
```
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 00_Vorlage Abschlussarbeit.tex
          post_compile: "latexmk -c"
```
